export const UPDATE_SINGLE_MACHINE = 'UPDATE_SINGLE_MACHINE';


// App.js 
export const RECEIVE_MACHINELIST = 'REQUEST_MACHINELIST';

export const REQUEST_MACHINELIST = 'REQUEST_MACHINELIST';

export const REQUEST_MACHINELIST_PENDING = 'REQUEST_MACHINELIST_PENDING';

export const REQUEST_MACHINELIST_SUCCESS = 'REQUEST_MACHINELIST_SUCCESS';

export const REQUEST_MACHINELIST_ERROR = 'REQUEST_MACHINELIST_ERROR';