export const UPDATE_SINGLE_MACHINE = 'UPDATE_SINGLE_MACHINE';


// App.js 
export const REQUEST_MACHINELIST_PENDING = 'REQUEST_MACHINELIST_PENDING';

export const REQUEST_MACHINELIST_SUCCESS = 'REQUEST_MACHINELIST_SUCCESS';

export const REQUEST_MACHINELIST_ERROR = 'REQUEST_MACHINELIST_ERROR';

export const WEBSOCKET_OPEN = 'WEBSOCKET_OPEN';

export const WEBSOCKET_MESSAGING = 'WEBSOCKET_MESSAGING';

export const WEBSOCKET_CLOSE = 'WEBSOCKET_CLOSE';